In [2]:
import numpy as np

In [5]:
import numpy as np
arr_1d=np.array([1,2,3,4,5,6])
arr_2d=np.array([[1,2,3],[4,5,6]])
arr_3d=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr_1d)
print('shape:',arr_1d.shape)
print('dimension:',arr_1d.ndim)
print('data type:',arr_1d.dtype)
print(arr_2d)
print('shape:',arr_2d.shape)
print('dimension:',arr_2d.ndim)
print('data type:',arr_2d.dtype)
print(arr_3d)
print('shape:',arr_3d.shape)
print('dimension:',arr_3d.ndim)
print('data type:',arr_3d.dtype)

[1 2 3 4 5 6]
shape: (6,)
dimension: 1
data type: int32
[[1 2 3]
 [4 5 6]]
shape: (2, 3)
dimension: 2
data type: int32
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
shape: (2, 2, 2)
dimension: 3
data type: int32


In [13]:
arr_1d=np.array([1,2,3,4,5,6,7,8])
arr_2d=arr_1d.reshape(2,4)
print('1d to 2d:\n',arr_2d)
arr_3d=arr_2d.reshape(2,2,2)
print('2d to 3d:\n',arr_3d)
reshaped_2d=arr_2d.reshape(4,2)
print('reshaped 2d:\n',reshaped_2d)

1d to 2d:
 [[1 2 3 4]
 [5 6 7 8]]
2d to 3d:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
reshaped 2d:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [8]:
import pandas as pd
arr1=np.zeros(10)
print(arr1)
arr2=np.ones((2,5), dtype=int)
print(arr2)
myarray2=np.arange(4,64,4,dtype=int).reshape(3,5)
print(myarray2)
arr=np.array([1,2,3,4])
tiled_arr=np.tile(arr,2)
series=pd.Series(tiled_arr)
print(series)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[1 1 1 1 1]
 [1 1 1 1 1]]
[[ 4  8 12 16 20]
 [24 28 32 36 40]
 [44 48 52 56 60]]
0    1
1    2
2    3
3    4
4    1
5    2
6    3
7    4
dtype: int32


In [37]:
ranarr=np.random.randint(0,5,size=(2,3))
print(ranarr)
onearr=np.ones((2,3),dtype=int)
print(onearr)
boolarr= ranarr > 2
print(boolarr)
print(boolarr.shape)
newarr=onearr[boolarr]
print(newarr)

[[3 1 2]
 [1 0 2]]
[[1 1 1]
 [1 1 1]]
[[ True False False]
 [False False False]]
(2, 3)
[1]


In [22]:
import numpy as np
rows = int(input("Enter number of rows: "))
cols = int(input("Enter number of columns: "))
m = np.zeros((rows, cols), dtype=int)
for i in range(rows):
    for j in range(cols):
        m[i, j] = int(input(f"Enter element ({i}, {j}): "))
n = np.sort(m, axis=1)
p = np.sort(n, axis=0)
print(p)
print('Enter the statistical operation:\n1.min\n2.max\n3.range\n4.percentile\n5.mean\n6.median\n7.variance\n8.std')
while True:
    op = int(input("\nEnter numerical choice: "))
    if op == 1:
        print("Minimum:", np.min(p))
    elif op == 2:
        print("Maximum:", np.max(p))
    elif op == 3:
        print("Range:", np.max(p) - np.min(p))
    elif op == 4:
        print("70th Percentile:", np.percentile(p, 70))
    elif op == 5:
        print("Mean:", np.mean(p))
    elif op == 6:
        print("Median:", np.median(p))
    elif op == 7:
        print("Variance:", np.var(p))
    elif op == 8:
        print("Standard Deviation:", np.std(p))
    else:
        print("Invalid operation!")
        break

[[2 4 6]
 [3 5 8]]
Enter the statistical operation:
1.min
2.max
3.range
4.percentile
5.mean
6.median
7.variance
8.std
Minimum: 2
Maximum: 8
Range: 6
70th Percentile: 5.5
70th Percentile: 5.5
Mean: 4.666666666666667
Median: 4.5
Variance: 3.888888888888889
Standard Deviation: 1.9720265943665387
Invalid operation!


In [30]:
import numpy as np
m = np.zeros((4,3), dtype=float)
for i in range(4):
    for j in range(3):
        m[i, j] = int(input(f"Enter element ({i}, {j}): "))
cm = m.mean(axis=0)
demeancol = m - cm
print("Original Matrix:\n", m)
print("Column Mean:\n", cm)
print("Demeaned Columns:\n", demeancol)


Original Matrix:
 [[2. 5. 3.]
 [7. 4. 8.]
 [4. 9. 2.]
 [0. 4. 7.]]
Column Mean:
 [3.25 5.5  5.  ]
Demeaned Columns:
 [[-1.25 -0.5  -2.  ]
 [ 3.75 -1.5   3.  ]
 [ 0.75  3.5  -3.  ]
 [-3.25 -1.5   2.  ]]


In [39]:
arr=np.array(['abc','bcd','cde'],dtype=np.str_)
print(np.char.join(' ',arr))



['a b c' 'b c d' 'c d e']


In [40]:
a1,a2=np.array([1,2,4,3,6,9]),np.array([1,2,5,3,8,7])
print('equal?',a1==a2)
print('not equal?',a1!=a2)
print('greater equal?',a1>=a2)
print('greater?',a1>a2)
print('less?',a1<a2)

equal? [ True  True False  True False False]
not equal? [False False  True False  True  True]
greater equal? [ True  True False  True False  True]
greater? [False False False False False  True]
less? [False False  True False  True False]


In [1]:
import numpy as np
m1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
m2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
print("Matrix 1:\n", m1)
print("Matrix 2:\n", m2)
print("Addition:\n", m1+m2)
print("Subtraction:\n", m1-m2)
print("Multiplication:\n", m1*m2)
print("Matrix Multiplication:\n", m1@m2)
print("Division:\n", m1/m2)
print("Transpose of Matrix 1:\n", m1.T)
print("Transpose of Matrix 2:\n", m2.T)

Matrix 1:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix 2:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]
Addition:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
Subtraction:
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
Multiplication:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]
Matrix Multiplication:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
Division:
 [[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]
Transpose of Matrix 1:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Transpose of Matrix 2:
 [[9 6 3]
 [8 5 2]
 [7 4 1]]
